---
- name: openscap setup
  hosts: openscap
  become: true
  become_user: root
  tasks:
  - name: ubuntu release name
    command: lsb_release -cs
    register: rel
  - name: install openscap-scanner
    apt:
      name: libopenscap8
      state: latest
  - name: validate installation
    shell: oscap --version | grep "command line tool"
    register: oscap_version
  - name: print oscap version
    debug: msg={{ oscap_version.stdout }}
  - name: print ubuntu release
    debug: msg={{ rel.stdout }}
  - name: Clone a repo with separate git directory
    ansible.builtin.git:
      repo: https://github.com/clabemo/OpenScap-Ubuntu.git
      dest: /var/tmp/openscap_scan.sh
  - name: Touch the same file, but add/remove some permissions
    ansible.builtin.file:
      path: /var/lib/kubelet/pods/dbb79503-eb86-4c3e-b426-c3be127ce995/volumes/kubernetes.io~empty-dir/awx-demo-projects/_12__openscap/openscap_scan.sh
      state: touch
      mode: 0755
  - name: Scan system for vulnerability
    shell: /var/tmp/openscap_scan.sh
