---
- name: openscap setup
  hosts: openscap
  become: true
  become_user: root
  tasks:
  - name: ubuntu release name
    command: lsb_release -cs
    register: rel
  - name: install openscap-scanner
    apt:
      name: libopenscap8
      state: latest
  - name: validate installation
    shell: oscap --version | grep "command line tool"
    register: oscap_version
  - name: print oscap version
    debug: msg={{ oscap_version.stdout }}
