---
- name: openscap setup
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: OS release name
    command: lsb_release -cs
    register: rel
  - name: install openscap-scanner
    apt:
      name: libopenscap8
      state: latest
  - name: validate installation
    shell: oscap --version | grep "command line tool"
    register: oscap_version
  - name: print oscap version
    debug: msg={{ oscap_version.stdout }}
  - name: print OS release
    debug: msg={{ rel.stdout }}
  - name: copy script
    copy:
      src: openscap_scan.sh
      dest: /var/tmp/openscap_scan.sh
      mode: 0755
  - name: Scan system for vulnerability
    shell: /var/tmp/openscap_scan.sh
